#!/usr/bin/env python3
"""
dralithus: A command  line tool to hydrate a network of virtual machines
"""
# Copyright 2023. Sumanth Vepa. svepa@milestone42.com
#
# This file is part of dralithus-core.
#
# dralithus-core is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dralithus-core is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dralithus-core. If not, see <https://www.gnu.org/licenses/>.

import sys

import yaml


def read_network_configuration(filename: str) -> dict:
  """ Read the contents of a dralithus network configuration file. """
  with open(filename, encoding='utf-8') as config_stream:
    return yaml.safe_load(config_stream)


def main():
  """
    Parse and print the contents of a file named network.yaml in the
    current directory.
  """
  try:
    config = read_network_configuration('network.yaml')
    print(type(config))
    print(config)
  except yaml.YAMLError as ex:
    print(ex, file=sys.stderr)
    sys.exit(1)
  sys.exit(0)


main()
