#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
  drl: Command line tool to deploy applications to various environments
"""
# -------------------------------------------------------------------
# drl: Command line tool to deply applications to various environments
#
# Copyright (C) 2023-25 Sumanth Vepa.
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License a
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
# -------------------------------------------------------------------
import sys

from dralithus.command import make
from dralithus.errors import DralithusError


def main(args: list[str]) -> int:
  """
    Parse the command line and execute the command

    :param args: The command line arguments (usually sys.argv, except
      in unit tests)
    :return: int: The exit code of the command
  """
  try:
    cmd = make(args)
    return cmd.execute()
  except DralithusError as ex:
    print(ex, file=sys.stderr)
    return ex.exit_code
  # Note that we are not catching any other exceptions here. This is
  # intentional. Any other exceptions are bugs in the code and should
  # not be caught. They should be fixed instead.


if __name__ == '__main__':
  sys.exit(main(sys.argv))
