#!/usr/bin/env python3
"""
  drl: Command line tool to deply applications to various environments
"""
import sys
import json

from dralithus.configuration import process_command_line


def main() -> None:
  """
    Parse the command line and print the environment name and the
    application name
  """
  configuration = process_command_line(sys.argv)
  print(json.dumps(configuration))


if __name__ == '__main__':
  main()
